### PR TITLE
Added pattern matching to #remove() and tests.

### PR DESCRIPTION
**Pull request by slaskis**
Hey, I was just about to write a caching module just like this! 

I had to add pattern matching to the manual remove (very useful for clearing out urls, some with queries etc) so I did some restructuring so the stores are accessible and I also added some tests (that pass, yay!).

Thought you might want it upstream too.

### CODE REVIEW

**Comment by mape** [comment]
Kanon!

**Comment by slaskis** [comment]
Läckert! Dags för en 0.2.0 snart då? ;)

**Comment by mape** [comment]
Hehe, missing any functionality? Or more tests? Guess there should be tests for non \* remove.

**Comment by slaskis** [comment]
Hehe, well I meant it would be nice to have it published to NPM.

**Comment by mape** [comment]
Oh it should be :)

```
time: 
   { '0.0.1': '2011-08-23T06:20:48.260Z',
     '0.0.2': '2011-08-23T20:44:16.896Z',
     '0.1.2': '2011-09-06T14:47:48.997Z' }
```

**Comment by slaskis** [comment]
Oh, I missed that, only looked at the package.json and saw it wasn't updated for 5 days... yay!

**Pull request merged**
